apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es
  namespace: demo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: myes
  data:
  - secretKey: hellolookatme
    remoteRef:
      key: vault/es
      property: key
