apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es
  namespace: demo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    # the genereated secret name
    name: myes
  data:
  - secretKey: hellolookatme # the genereate file name
    remoteRef:
      key: vault/es # the secret path in vault, the full path will include the secret engine as prefix, eg. /demo/vault/es
      property: key # the key of the secret
