apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: demo
spec:
  provider:
    vault:
      server: "http://192.168.56.50:8200"
      path: "demo"
      version: "v2"
      auth:
        kubernetes:
          # Path where the Kubernetes authentication backend is mounted in Vault
          mountPath: "kubernetes"
          # A required field containing the Vault Role to assume.
          role: "demo"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
          #serviceAccountRef:
          #  name: "default"
          #secretRef:
          #  name: "vault-token-g999r"
          #  namespace: "vault"
